name: geocat_comp_build
channels:
  - conda-forge
dependencies:
  - python>=3.8, <3.11
  - cf_xarray>=0.3.1
  - cftime
  - dask
  - distributed
  - eofs
  - geocat-f2py
  - metpy
  - numpy
  - pint<0.20
  - pre-commit
  - xarray
  - xskillscore
# Packages listed below are for testing
  - geocat-datafiles
  - netcdf4
  - pytest
  - pytest-cov
