name: geocat_comp_build
channels:
  - conda-forge
  - ncar
dependencies:
  - python=3.7
  - cf_xarray >= 0.3.1
  - dask
  - distributed
  - eofs
  - geocat-f2py
  - netcdf4
  - numpy
  - pytest
  - xarray
