name: geocat_comp_build
channels:
  - conda-forge
dependencies:
  - python>=3.8, <3.11
  - cf_xarray>=0.3.1
  - cftime
  - dask
  - distributed
  - eofs
  - geocat-datafiles  # for tests
  - geocat-f2py
  - metpy
  - netcdf4  # for tests
  - numpy
  - pint<0.20
  - pre-commit
  - pytest  # for tests
  - pytest-cov  # for tests
  - xarray
  - xskillscore
