name: geocat-comp-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - cf_xarray >= 0.3.1
  - dask
  - distributed
  - eofs
  - geocat-f2py
  - netcdf4
  - numpy
  - pytest
  - xarray
  - netcdf4
