# This is the main workflow for branches and pull requests.
name: main

# Controls when the action will run. Triggers the workflow on push or pull request
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job for running autopep8 on ubuntu
  autopep8:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
          with:
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
            ref: ${{ github.head_ref }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@github.com'
          git commit -am "Automated autopep8 fixes"
          git push
